### PR TITLE
showing past 5days

### PR DESCRIPTION
**Pull request by olgaratu**

### CODE REVIEW

**Comment by HodaSheikh** [comment]
I reviewed the codes for LGTM. all thing about removing the unnecessary things and also updated coordinator, sensors, db and front end to show previous 5 days and made axis ticks for visible are all good and I didn't saw any conlict. please publish them.

**Comment by HodaSheikh** [comment]
Just one thing I want to ask is, is it possible to show the "status value"("Extreme", "Very High", "High", "Moderate", "Low") of each index on the dashboard? now it is just showing the diffrnce by colors which may cause confusion for users as i asked 3 users for usability test. 
or for example we show the value of index is 4(current)/8(max) for each index

**Comment by olgaratu** [comment]
> I reviewed the codes for LGTM. all thing about removing the unnecessary things and also updated coordinator, sensors, db and front end to show previous 5 days and made axis ticks for visible are all good and I didn't saw any conlict. please publish them.

Hi, thank you for feedback, but it has merge conflict and it visible in the pull request, also it is marked as draft (so it won't be merged again without authors permission).
I asked Mislav to check how it works on his side and if my changes were ok with him, he will check it later and I will merge it then.


> Just one thing I want to ask is, is it possible to show the "status value"("Extreme", "Very High", "High", "Moderate", "Low") of each index on the dashboard? now it is just showing the difference by colours which may cause confusion for users as i asked 3 users for usability test. or for example we show the value of index is 4(current)/8(max) for each index

Thank you for doing usability testing. Can we see any documentation done for it? What was measured or asked from user?

 It was done this way as it is now, because sensors previously showed only category which are different for each  type  of sensor and missed lots of other attributes that were available from APIs, it will be changed after merging this branch as other attributes were discovered and sensors will have category value which can be easily remapped in the front end card. Would you like to contribute by doing that? It is not difficult at all
 
 Also descriptions can be easily fetched and displayed in some kind of box under or above the plot, I tried to add one and it worked, I can send you  html code for one and you can just add all of them there

**Review by HodaSheikh — APPROVED** [review]
thank you for adding the description in hovers.

**Comment by HodaSheikh** [comment]
Iqra and me worked on the user usability test and the document will be added to the report after the Fair.

**Comment by olgaratu** [comment]
> thank you for adding the description in hovers.

You are welcome, they can also be found in a box below the plot, together with changes that you (your users) requested  earlier from me. Can you verify that it works on your machine?

**Comment by olgaratu** [comment]
> Iqra and me worked on the user usability test and the document will be added to the report after the Fair.

Ok, we will wait.

**Pull request merged**
